/**
 * Direção visual: Laboratório Neon Editorial.
 * Papel: aulas práticas, referências oficiais, geração local de workflow e exemplo de execução.
 */
import { useState } from "react";
import { Check, Copy, ExternalLink, PlayCircle, Terminal, X } from "lucide-react";
import { Button } from "@/components/ui/button";

type PackageManager = "npm" | "pnpm" | "yarn";

const lessons = [
  { title: "Seletores", summary: "Encontre elementos de forma estável e legível.", text: "Antes de clicar ou preencher algo, o Cypress precisa localizar o elemento. Prefira atributos dedicados, como data-testid, quando a interface oferece esse contrato. Use cy.get() para um seletor e cy.contains() para texto visível.", code: `cy.get('[data-testid=produto]').should('be.visible')\ncy.contains('Adicionar').click()`, docs: "https://docs.cypress.io/app/core-concepts/best-practices#Selecting-Elements" },
  { title: "Assertions", summary: "Transforme o Then em uma verificação observável.", text: "Uma assertion, ou verificação, declara o estado esperado. O .should() é encadeado a um comando anterior e é repetido até passar ou atingir o tempo limite. No Gherkin, ele costuma representar o Then.", code: `cy.get('[data-testid=carrinho]')\n  .should('be.visible')\n  .and('contain', 'Produto')`, docs: "https://docs.cypress.io/api/commands/should" },
  { title: "Fixtures", summary: "Separe dados reutilizáveis do comportamento do teste.", text: "Fixtures são arquivos estáticos em cypress/fixtures. Use cy.fixture() para carregar dados conhecidos e mantê-los separados da intenção do cenário. Um arquivo pequeno e específico é mais fácil de entender e manter.", code: `cy.fixture('produto.json').then((produto) => {\n  cy.intercept('GET', '/api/produtos', { body: [produto] })\n})`, docs: "https://docs.cypress.io/api/commands/fixture" },
  { title: "Interceptação", summary: "Observe ou controle o tráfego de rede.", text: "cy.intercept() pode observar uma rota ou devolver uma resposta controlada. Use .as() para dar um nome à rota e cy.wait() quando o comportamento depende do fim da requisição.", code: `cy.intercept('GET', '/api/carrinho').as('carregarCarrinho')\ncy.visit('/carrinho')\ncy.wait('@carregarCarrinho')\n  .its('response.statusCode').should('eq', 200)`, docs: "https://docs.cypress.io/api/commands/intercept" },
];

const scenarios = [
  ["Adicionar produto ao carrinho", "carrinho.cy.js", true, "Produto visível no carrinho"],
  ["Atualizar total do pedido", "carrinho.cy.js", false, "Esperado R$ 89,90 · encontrado R$ 0,00"],
  ["Finalizar pedido autenticado", "checkout.cy.js", true, "URL /pedido/confirmado"],
  ["Exibir erro de estoque", "estoque.cy.js", false, "Elemento [data-testid=alerta-estoque] não encontrado"],
] as const;

const workflows: Record<PackageManager, string> = {
  npm: `name: Testes de regressão\non:\n  pull_request:\n  schedule:\n    - cron: '0 3 * * 1-5'\njobs:\n  cypress:\n    runs-on: ubuntu-24.04\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm ci\n      - uses: cypress-io/github-action@v7\n        with:\n          build: npm run build\n          start: npm start\n          browser: chrome`,
  pnpm: `name: Testes de regressão\non:\n  pull_request:\n  schedule:\n    - cron: '0 3 * * 1-5'\njobs:\n  cypress:\n    runs-on: ubuntu-24.04\n    steps:\n      - uses: actions/checkout@v4\n      - uses: pnpm/action-setup@v4\n        with:\n          version: 10\n      - run: pnpm install --frozen-lockfile\n      - uses: cypress-io/github-action@v7\n        with:\n          build: pnpm build\n          start: pnpm start\n          browser: chrome`,
  yarn: `name: Testes de regressão\non:\n  pull_request:\n  schedule:\n    - cron: '0 3 * * 1-5'\njobs:\n  cypress:\n    runs-on: ubuntu-24.04\n    steps:\n      - uses: actions/checkout@v4\n      - run: corepack enable\n      - run: yarn install --immutable\n      - uses: cypress-io/github-action@v7\n        with:\n          build: yarn build\n          start: yarn start\n          browser: chrome`,
};

function CopyBlock({ label, code }: { label: string; code: string }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1800);
  };
  return <div className="overflow-hidden rounded-xl border border-white/10 bg-[#090b10]"><div className="flex items-center justify-between border-b border-white/10 px-4 py-2"><span className="font-mono text-[10px] uppercase tracking-[.12em] text-[#777380]">{label}</span><button onClick={copy} className="inline-flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-[.1em] text-[#18d8e8] hover:text-white" aria-label={`Copiar ${label}`}>{copied ? <><Check className="h-3.5 w-3.5" /> Copiado!</> : <><Copy className="h-3.5 w-3.5" /> Copiar</>}</button></div><pre className="overflow-x-auto p-4 font-mono text-xs leading-6 text-[#d9d2e2]"><code>{code}</code></pre></div>;
}

export default function CypressLearningPanel() {
  const [packageManager, setPackageManager] = useState<PackageManager>("npm");
  const [running, setRunning] = useState(false);
  const run = () => { setRunning(false); window.setTimeout(() => setRunning(true), 350); };
  return <div className="mt-10 space-y-10 border-t border-white/10 pt-10">
    <section><div className="eyebrow">ANTES DE COMEÇAR</div><h2 className="mt-3 font-display text-3xl font-bold tracking-[-.04em]">O caminho para o primeiro teste.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#96919f]">Você não precisa saber Cypress para começar. Siga a ordem: tenha as ferramentas, crie o projeto, abra o Cypress e só depois escreva o teste.</p><div className="mt-6 grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-white/10 bg-[#11131a] p-5"><span className="font-mono text-[10px] text-[#18d8e8]">01 / FERRAMENTAS</span><h3 className="mt-3 font-display font-semibold">Node.js e editor</h3><p className="mt-2 text-xs leading-5 text-[#96919f]">Instale o Node.js, escolha um editor de código e abra o terminal na pasta do projeto.</p></div><div className="rounded-xl border border-white/10 bg-[#11131a] p-5"><span className="font-mono text-[10px] text-[#f34ba8]">02 / PROJETO</span><h3 className="mt-3 font-display font-semibold">Dependência local</h3><p className="mt-2 text-xs leading-5 text-[#96919f]">O Cypress fica instalado no projeto. Assim, o time usa a mesma versão ao executar os testes.</p></div><div className="rounded-xl border border-white/10 bg-[#11131a] p-5"><span className="font-mono text-[10px] text-[#ff9a72]">03 / ROTINA</span><h3 className="mt-3 font-display font-semibold">Especificação e prova</h3><p className="mt-2 text-xs leading-5 text-[#96919f]">Cada cenário Gherkin vira uma sequência de preparação, ação e verificação observável.</p></div></div></section>
    <section><div className="eyebrow">AULAS / APRENDER FAZENDO</div><h2 className="mt-3 font-display text-3xl font-bold tracking-[-.04em]">Quatro assuntos para praticar.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#96919f]">Leia a intenção em português, copie o exemplo e confirme na documentação oficial o que o comando recebe e devolve.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{lessons.map((lesson, index) => <article key={lesson.title} className="rounded-xl border border-white/10 bg-[#11131a] p-5"><div className="flex items-start justify-between gap-3"><div><span className="font-mono text-[10px] text-[#18d8e8]">AULA 0{index + 1}</span><h3 className="mt-2 font-display text-lg font-semibold">{lesson.title}</h3></div><a href={lesson.docs} target="_blank" rel="noreferrer" aria-label={`Abrir documentação oficial de ${lesson.title}`} className="text-[#ff82c0] hover:text-white"><ExternalLink className="h-4 w-4" /></a></div><p className="mt-3 text-sm leading-6 text-[#c5c1cd]">{lesson.summary}</p><p className="mt-3 text-xs leading-5 text-[#96919f]">{lesson.text}</p><div className="mt-4"><CopyBlock label={`exemplo / ${lesson.title.toLowerCase()}`} code={lesson.code} /></div></article>)}</div></section>
    <section className="grid gap-8 border-t border-white/10 pt-10 lg:grid-cols-[.85fr_1.15fr]"><div><div className="eyebrow">CI/CD / GERADOR</div><h2 className="mt-3 font-display text-3xl font-bold tracking-[-.04em]">Monte seu workflow.</h2><p className="mt-3 text-sm leading-6 text-[#96919f]">CI/CD é a rotina que instala, prepara e testa o projeto automaticamente. Escolha npm, pnpm ou yarn para gerar o arquivo.</p><label className="mt-5 block font-mono text-[10px] uppercase tracking-[.12em] text-[#777380]">Gerenciador de pacotes<select value={packageManager} onChange={(event) => setPackageManager(event.target.value as PackageManager)} className="mt-2 w-full rounded-lg border border-white/15 bg-[#0d0f14] px-3 py-3 text-sm normal-case tracking-normal text-[#18d8e8] outline-none focus:border-[#18d8e8]"><option value="npm">npm</option><option value="pnpm">pnpm</option><option value="yarn">yarn</option></select></label><div className="mt-5 rounded-xl border border-[#f34ba8]/20 bg-[#19121b] p-4"><p className="text-xs leading-5 text-[#c5b8c2]">O cron `0 3 * * 1-5` executa de segunda a sexta às 03:00 UTC. Ajuste o horário ao fuso do time.</p></div></div><div><CopyBlock label={`.github/workflows/cypress-regressao.yml / ${packageManager}`} code={workflows[packageManager]} /><div className="mt-3 flex flex-wrap gap-3"><a href="https://docs.cypress.io/app/continuous-integration/github-actions" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.1em] text-[#18d8e8] hover:underline">Documentação Cypress CI <ExternalLink className="h-3 w-3" /></a><a href="https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#schedule" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.1em] text-[#ff82c0] hover:underline">Documentação schedule <ExternalLink className="h-3 w-3" /></a></div></div></section>
    <section className="border-t border-white/10 pt-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">SIMULAÇÃO / REGRESSÃO</div><h2 className="mt-3 font-display text-3xl font-bold tracking-[-.04em]">Veja a suíte rodar.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#96919f]">Verde representa cenário aprovado; coral aponta o primeiro ponto que precisa de investigação.</p></div><Button onClick={run} className="gap-2 bg-[#f34ba8] text-[#1a0714] hover:bg-[#ff74bc]"><PlayCircle className="h-4 w-4" /> {running ? "Rodar novamente" : "Executar regressão"}</Button></div><div className="mt-6 rounded-xl border border-white/10 bg-[#0d0f14] p-5"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className={`h-2.5 w-2.5 rounded-full ${running ? "bg-[#18d8e8]" : "bg-[#777380]"}`} /><span className="font-mono text-[10px] uppercase tracking-[.14em] text-[#a9a5b3]">{running ? "EXECUÇÃO CONCLUÍDA" : "AGUARDANDO EXECUÇÃO"}</span></div>{running && <div className="flex gap-4 font-mono text-[10px]"><span className="text-[#18d8e8]">02 aprovados</span><span className="text-[#ff9a72]">02 falhos</span></div>}</div>{running ? <div className="space-y-2">{scenarios.map(([name, spec, passed, detail]) => <div key={name} className={`flex flex-wrap items-center gap-3 rounded-lg border p-3 ${passed ? "border-[#18d8e8]/20 bg-[#18d8e8]/5" : "border-[#ff9a72]/25 bg-[#ff9a72]/5"}`}><span className={`grid h-7 w-7 place-items-center rounded-full ${passed ? "bg-[#18d8e8]/15 text-[#18d8e8]" : "bg-[#ff9a72]/15 text-[#ff9a72]"}`}>{passed ? <Check className="h-4 w-4" /> : <X className="h-4 w-4" />}</span><div className="min-w-[220px] flex-1"><p className="text-sm font-medium text-[#e9e5ee]">{name}</p><p className="mt-1 font-mono text-[10px] text-[#777380]">{spec} · exemplo local</p></div><span className={`text-xs ${passed ? "text-[#9decef]" : "text-[#ffc1ac]"}`}>{detail}</span></div>)}</div> : <div className="grid min-h-[170px] place-items-center rounded-lg border border-dashed border-white/10 text-center"><div><Terminal className="mx-auto h-7 w-7 text-[#777380]" /><p className="mt-3 text-sm text-[#96919f]">Clique em executar para acompanhar o resumo da suíte.</p><p className="mt-1 text-xs text-[#777380]">Os resultados acima são um exemplo de leitura da saída.</p></div></div>}</div></section>
  </div>;
}
